- name: Test
  run: dotnet test  -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal chatguy-nlp.Tests/
      
- name: Create Test Coverage Badge
  uses: simon-k/dotnet-code-coverage-badge@v1.0.0
  id: create_coverage_badge
  with:
    label: Unit Test Coverage
    color: brightgreen
    path: chatguy-nlp/Tests/TestResults/coverage.opencover.xml
    gist-filename: code-coverage.json
    gist-id: 4e3721eede9c6f0753da666369967529
    gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}   