name: CoverageBadge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'     
    steps:
      - uses: actions/checkout@v2

      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v1.8
